const ideasData = [
    {
        title: "Smart Soil Regen Tiles",
        shortDescription: "Tiles heal soil with sensors and microbes.",
        technology: "IoT, Biotech",
        values: "Regeneration",
        problemAddressed: "Soil degradation affects 40% of global farmland, slashing yields and resilience.",
        solutionDetails: "Hexagonal tiles (1m²) embed sensors for moisture/pH and release microbial cultures to rebuild soil health. Solar-powered, they sync to a farmer app for real-time data.",
        potentialScale: "Deployable on 1M acres in 5 years, boosting yields 30%.",
        milestonesForCapital: "1) Prototype tested on 10 farms; 2) 1,000 tiles deployed with 20% yield increase; 3) Scale to 100,000 acres.",
        teamNeeds: "Soil scientists, IoT engineers, app developers.",
        score: 89,
        valueScore: 35,
        innovationScore: 36,
        applicabilityScore: 18
    },
    {
        title: "Nomadic Microgrids",
        shortDescription: "Mobile solar units power remote areas.",
        technology: "Renewables, Blockchain",
        values: "Equity",
        problemAddressed: "800M people lack electricity, stunting development.",
        solutionDetails: "Truck-mounted solar/wind units (5kW each) roll into remote areas. Blockchain tracks energy credits, incentivizing surplus sharing.",
        potentialScale: "50,000 homes powered in 3 years across 10 regions.",
        milestonesForCapital: "1) 10-unit pilot in one village; 2) 100 units deployed, 90% uptime; 3) 1,000 units active.",
        teamNeeds: "Renewable engineers, blockchain devs, logistics experts.",
        score: 86,
        valueScore: 34,
        innovationScore: 35,
        applicabilityScore: 17
    },
    {
        title: "Modular Train Systems",
        shortDescription: "Raised trains with solar, wind, farming, and rewilding. Free energy, wildlife thrives.",
        technology: "Renewables, Transport",
        values: "Sustainability",
        problemAddressed: "Transport emissions and land loss disrupt climate and farming.",
        solutionDetails: "Raised tracks with solar panels (500W/m²), wind turbines below, and farming/re-wilding underneath. Trains switch between rail and road with minimal wildlife impact.",
        potentialScale: "1,000km of track, powering 100,000 homes and feeding 50,000 people.",
        milestonesForCapital: "1) 10km prototype built; 2) 100km operational with energy/farm outputs; 3) 500km scaled.",
        teamNeeds: "Transport engineers, renewable experts, ecologists.",
        score: 84,
        valueScore: 32,
        innovationScore: 34,
        applicabilityScore: 18
    },
    {
        title: "Regenerative Bots",
        shortDescription: "Bots apply permaculture to farming at scale.",
        technology: "Robotics, Agriculture",
        values: "Regeneration",
        problemAddressed: "Industrial farming depletes soil and limits scalability of permaculture.",
        solutionDetails: "Autonomous bots (1m wide) plant, tend, and harvest using permaculture patterns. Solar-powered, they adapt to terrain via AI.",
        potentialScale: "10,000 bots on 500,000 acres, doubling soil carbon in a decade.",
        milestonesForCapital: "1) 10-bot pilot on 100 acres; 2) 100 bots with 25% yield gain; 3) 1,000 bots deployed.",
        teamNeeds: "Robotics engineers, permaculture experts, AI developers.",
        score: 83,
        valueScore: 33,
        innovationScore: 33,
        applicabilityScore: 17
    },
    {
        title: "Waste-to-Wear Threads",
        shortDescription: "Plastic waste becomes clothing.",
        technology: "Recycling, AI Design",
        values: "Creativity",
        problemAddressed: "10M tons of plastic waste clog landfills yearly.",
        solutionDetails: "Machines shred plastic into fibers, spun into thread by solar-powered looms. AI designs culturally resonant patterns.",
        potentialScale: "Divert 1M tons, clothe 2M people annually.",
        milestonesForCapital: "1) Prototype machine processes 1 ton; 2) 10 machines, 100 tons diverted; 3) 100 machines scaled.",
        teamNeeds: "Recycling techs, textile designers, AI specialists.",
        score: 81,
        valueScore: 34,
        innovationScore: 31,
        applicabilityScore: 16
    },
    {
        title: "AI Coral Reef Builders",
        shortDescription: "Robots 3D-print coral scaffolds.",
        technology: "Robotics, Marine Biology",
        values: "Biodiversity",
        problemAddressed: "Coral loss threatens 25% of marine life and coastal protection.",
        solutionDetails: "Submersible robots 3D-print scaffolds (bio-cement), seeded with polyps. Drones optimize water flow.",
        potentialScale: "Regrow 50km of reefs in 5 years, protecting 10M coastal residents.",
        milestonesForCapital: "1) 1km scaffold tested; 2) 10km with 80% polyp survival; 3) 50km scaled.",
        teamNeeds: "Marine biologists, robotics engineers, drone operators.",
        score: 81,
        valueScore: 30,
        innovationScore: 34,
        applicabilityScore: 17
    },
    {
        title: "Water-Web Cities",
        shortDescription: "AI grids purify rainwater for urban use.",
        technology: "Water Tech, Clean Energy",
        values: "Resilience",
        problemAddressed: "Urban water scarcity affects 1B people.",
        solutionDetails: "Rooftop pipes harvest rain, biofilters purify it, AI grids distribute it. Excess powers hydrogen buses.",
        potentialScale: "Supply 5M urbanites, cut emissions by 10% in 20 cities.",
        milestonesForCapital: "1) Pilot in 1 city block; 2) 10 blocks with 90% efficiency; 3) Full city rollout.",
        teamNeeds: "Water engineers, AI specialists, urban planners.",
        score: 79,
        valueScore: 31,
        innovationScore: 32,
        applicabilityScore: 16
    },
    {
        title: "Eco-Sound Highways",
        shortDescription: "Roads generate energy, support pollinators.",
        technology: "Energy Harvesting, Ecology",
        values: "Circularity",
        problemAddressed: "Traffic noise and energy waste plague roads.",
        solutionDetails: "Piezoelectric roads (1kW/km) generate power from vibrations. Barriers host pollinator plants, AI tunes noise reduction.",
        potentialScale: "5,000km of roads, powering 200,000 homes.",
        milestonesForCapital: "1) 1km test road; 2) 50km with energy/pollinator gains; 3) 1,000km scaled.",
        teamNeeds: "Energy engineers, ecologists, acoustic experts.",
        score: 78,
        valueScore: 30,
        innovationScore: 31,
        applicabilityScore: 17
    },
    {
        title: "Floating Food Forests",
        shortDescription: "Buoyant platforms grow food with tidal energy.",
        technology: "Hydroponics, Renewables",
        values: "Balance",
        problemAddressed: "Coastal food insecurity and land scarcity.",
        solutionDetails: "100m² platforms use hydroponics and tidal energy. AI optimizes crop cycles, delivers to shore.",
        potentialScale: "1,000 platforms feeding 500,000 people yearly.",
        milestonesForCapital: "1) 1 platform operational; 2) 10 platforms with 50 tons output; 3) 100 platforms scaled.",
        teamNeeds: "Hydroponics experts, maritime engineers, AI devs.",
        score: 77,
        valueScore: 28,
        innovationScore: 32,
        applicabilityScore: 17
    },
    {
        title: "Rewilding Swarm Networks",
        shortDescription: "Drones reforest with satellite tracking.",
        technology: "Drones, Carbon Markets",
        values: "Restoration",
        problemAddressed: "Deforestation wipes out 10M hectares yearly.",
        solutionDetails: "Biodegradable drone swarms (100 units) plant seeds and spray nutrients. Satellites track growth for carbon credits.",
        potentialScale: "Reforest 1M hectares in 5 years, 500Mt CO2 captured.",
        milestonesForCapital: "1) 100-hectare pilot; 2) 10,000 hectares with 70% survival; 3) 100,000 hectares scaled.",
        teamNeeds: "Drone engineers, forestry experts, satellite analysts.",
        score: 77,
        valueScore: 29,
        innovationScore: 33,
        applicabilityScore: 15
    },
    {
        title: "Ocean Energy Harvesters",
        shortDescription: "Drones clean plastic, harvest wave energy.",
        technology: "AI, Ocean Tech",
        values: "Restoration",
        problemAddressed: "Ocean plastic and energy poverty in coastal zones.",
        solutionDetails: "Drones (2m wide) collect plastic and convert wave energy (500W/unit). AI maps cleanup zones.",
        potentialScale: "Clear 500,000 tons of plastic, power 50,000 homes.",
        milestonesForCapital: "1) 10-drone pilot; 2) 100 drones with 1,000 tons cleared; 3) 1,000 drones scaled.",
        teamNeeds: "Ocean techs, AI engineers, energy specialists.",
        score: 75,
        valueScore: 28,
        innovationScore: 31,
        applicabilityScore: 16
    },
    {
        title: "Bio-Mimetic Urban Cooling Drones",
        shortDescription: "Drones cool cities, reforest rooftops.",
        technology: "AI, Drones",
        values: "Harmony",
        problemAddressed: "Urban heat islands raise temps by 5°C+.",
        solutionDetails: "Solar-powered drones (1m span) mist water and drop seeds, mimicking bird flocks. AI targets hotspots.",
        potentialScale: "Cool 50 cities, reforest 10,000 rooftops in 3 years.",
        milestonesForCapital: "1) 10-drone city test; 2) 100 drones, 2°C drop; 3) 1,000 drones scaled.",
        teamNeeds: "Drone engineers, urban ecologists, AI devs.",
        score: 74,
        valueScore: 27,
        innovationScore: 30,
        applicabilityScore: 17
    },
    {
        title: "Sky Farming Towers",
        shortDescription: "Balloon-tethered farms feed cities.",
        technology: "Aerospace, Robotics",
        values: "Innovation",
        problemAddressed: "Land scarcity limits urban food supply.",
        solutionDetails: "50m-high balloon towers grow crops hydroponically. Robots tend and deliver harvests.",
        potentialScale: "Feed 1M city dwellers, free 5,000 acres of land.",
        milestonesForCapital: "1) 1-tower prototype; 2) 5 towers with 100 tons output; 3) 50 towers scaled.",
        teamNeeds: "Aerospace engineers, robotics experts, hydroponics specialists.",
        score: 72,
        valueScore: 25,
        innovationScore: 31,
        applicabilityScore: 16
    },
    {
        title: "Atmospheric Water Harvesting Microforests",
        shortDescription: "Self-sustaining urban oases collect water from air.",
        technology: "Biomimicry, Urban Tech",
        values: "Sustainability",
        problemAddressed: "Water scarcity affects billions while urban environments suffer from heat island effects.",
        solutionDetails: "Biomimetic water harvesting structures integrated with specially designed microforests create self-sustaining urban oases that collect atmospheric moisture, cool surroundings, and support biodiversity.",
        potentialScale: "Each hectare could produce 500-1,000 liters of water daily while lowering local temperatures by 2-4°C and supporting hundreds of species.",
        milestonesForCapital: "1) Single functional prototype in arid environment; 2) 10-unit neighborhood installation; 3) City-wide network with water distribution system.",
        teamNeeds: "Biomimicry specialists, urban foresters, hydrology engineers, materials scientists, municipal planners.",
        score: 86,
        valueScore: 33,
        innovationScore: 35,
        applicabilityScore: 18
    },
    {
        title: "Collective Human-AI Biosphere Stewardship",
        shortDescription: "AI-human platforms co-design ecological restoration.",
        technology: "AI, Conservation",
        values: "Harmony",
        problemAddressed: "Ecological restoration projects often fail due to disconnection from local knowledge and values.",
        solutionDetails: "Platforms merge human wisdom with AI analysis to co-design ecological regeneration projects where traditional knowledge, cultural values, and cutting-edge science work together to restore degraded ecosystems.",
        potentialScale: "Could transform management approaches for up to 30% of Earth's surface over 20 years through distributed stewardship models.",
        milestonesForCapital: "1) Platform prototype with 10 communities; 2) Regional deployment across 100 ecosystems; 3) Global platform connecting 10,000+ stewardship initiatives.",
        teamNeeds: "AI ethicists, indigenous knowledge specialists, ecological modelers, community organizers, conservation biologists.",
        score: 84,
        valueScore: 29,
        innovationScore: 37,
        applicabilityScore: 18
    },
    {
        title: "Adaptive Climate-Resilient Seed Banks",
        shortDescription: "Mobile AI-managed seed vaults protect crop diversity.",
        technology: "AI, Agriculture",
        values: "Resilience",
        problemAddressed: "Climate change threatens agricultural biodiversity and food security in vulnerable regions.",
        solutionDetails: "Mobile, AI-managed seed vaults use drones to distribute climate-adapted crop seeds to vulnerable regions. The system continuously learns from environmental data to evolve seed selections and preservation strategies.",
        potentialScale: "Could preserve thousands of crop varieties while enhancing food security for 100M+ people in climate-vulnerable regions.",
        milestonesForCapital: "1) Prototype seed vault with initial AI algorithms; 2) Regional deployment with drone distribution network; 3) Multi-continental system with predictive adaptation capabilities.",
        teamNeeds: "Agricultural geneticists, AI specialists, drone engineers, climate scientists, local agricultural extension workers.",
        score: 83,
        valueScore: 30,
        innovationScore: 35,
        applicabilityScore: 18
    },
    {
        title: "Bioelectric Reef Restoration",
        shortDescription: "Wave-powered electric fields accelerate reef growth.",
        technology: "Marine Tech, Clean Energy",
        values: "Regeneration",
        problemAddressed: "Coral reefs are dying worldwide due to climate change and local stressors.",
        solutionDetails: "Low-voltage electrical fields powered by wave energy accelerate coral calcification rates while repelling certain invasive species. Systems create 'safe zones' where reefs can recover at 3-5x natural rates.",
        potentialScale: "Could restore 20% of degraded reefs within two decades, protecting coastlines and preserving marine biodiversity hotspots.",
        milestonesForCapital: "1) Lab validation of optimal electrical parameters; 2) Protected bay deployment of 1 hectare; 3) Open ocean system with 100 hectare coverage.",
        teamNeeds: "Marine biologists, electrical engineers, oceanographers, materials scientists specializing in saltwater applications.",
        score: 83,
        valueScore: 31,
        innovationScore: 34,
        applicabilityScore: 18
    },
    {
        title: "Emergent AI Agricultural Collectives",
        shortDescription: "AI coordinates regenerative farm networks.",
        technology: "AI, Agriculture",
        values: "Collaboration",
        problemAddressed: "Small-scale regenerative farms struggle with market access and production optimization.",
        solutionDetails: "AI systems coordinate independent farmer networks to optimize ecological health and market efficiency simultaneously, balancing supply, predicting demand, and maximizing ecosystem services.",
        potentialScale: "Could connect 1M+ small farms into resilient networks, improving livelihoods while regenerating 10M+ hectares of agricultural land.",
        milestonesForCapital: "1) 100-farm pilot collective; 2) Regional network of 1,000 farms; 3) Multi-regional system with cross-border capabilities.",
        teamNeeds: "AI experts, agricultural economists, regenerative farming specialists, logistics engineers, rural sociologists.",
        score: 80,
        valueScore: 30,
        innovationScore: 32,
        applicabilityScore: 18
    },
    {
        title: "RegenPods: Portable Soil Restoration Units",
        shortDescription: "Solar-powered units restore degraded soil.",
        technology: "Biotech, IoT",
        values: "Regeneration",
        problemAddressed: "Small farmers lack access to soil restoration technologies, leading to degraded land and poor yields.",
        solutionDetails: "Compact, solar-powered units analyze soil health with embedded sensors and dispense tailored mixes of biochar, compost tea, and beneficial microbes. An accompanying app provides guidance and tracks improvements.",
        potentialScale: "Could restore millions of hectares of degraded farmland while improving livelihoods for 100M+ small-scale farmers globally.",
        milestonesForCapital: "1) Functional prototype with proven soil improvement; 2) Regional deployment of 1,000 units with data collection; 3) Manufacturing scale-up with rental/distribution network.",
        teamNeeds: "Soil scientists, agricultural engineers, solar technology specialists, mobile app developers, microbiologists.",
        score: 80,
        valueScore: 34,
        innovationScore: 30,
        applicabilityScore: 16
    },
    {
        title: "Urban Air Purifiers: Living Walls with Microbial Filters",
        shortDescription: "Smart living walls clean city air.",
        technology: "Biotech, IoT",
        values: "Health",
        problemAddressed: "Urban air pollution causes significant health problems, especially in low-income neighborhoods.",
        solutionDetails: "Modular living walls with photosynthetic bacteria and plants absorb pollutants like CO2, nitrogen oxides, and particulate matter. IoT sensors monitor air quality in real-time, optimizing water and nutrient delivery.",
        potentialScale: "Could improve air quality for millions of urban residents while reducing respiratory disease rates by 15-25% in deployed areas.",
        milestonesForCapital: "1) Pilot installation with verified air quality improvement; 2) Neighborhood-scale deployment across 100 buildings; 3) City-wide implementation with health impact data.",
        teamNeeds: "Microbiologists, environmental engineers, urban planners, IoT specialists, public health researchers.",
        score: 79,
        valueScore: 30,
        innovationScore: 32,
        applicabilityScore: 17
    },
    {
        title: "Biohybrid Pollution Sensors",
        shortDescription: "Living sensors detect and clean pollution.",
        technology: "Biotech, Nanotech",
        values: "Innovation",
        problemAddressed: "Environmental contamination often goes undetected until causing significant harm.",
        solutionDetails: "Living organisms (bacteria or plant cells) combined with nanomaterials create self-powered sensing networks that detect pollution and initiate remediation processes, signaling their status through bioluminescent outputs.",
        potentialScale: "Networks could monitor millions of square kilometers of waterways and soil with minimal infrastructure while actively beginning cleanup processes.",
        milestonesForCapital: "1) Lab demonstration of detection capabilities; 2) Field test in controlled contaminated site; 3) Watershed-scale deployment.",
        teamNeeds: "Synthetic biologists, environmental engineers, nanotechnology specialists, sensor network designers.",
        score: 77,
        valueScore: 26,
        innovationScore: 33,
        applicabilityScore: 18
    },
    {
        title: "Mycelium-Based Carbon Sequestration Networks",
        shortDescription: "Smart fungal networks capture carbon.",
        technology: "Biotech, IoT",
        values: "Regeneration",
        problemAddressed: "Carbon dioxide levels continue rising while soil health deteriorates globally.",
        solutionDetails: "Engineered mycelium networks with embedded IoT sensors create living carbon sinks that monitor their own effectiveness. These underground networks communicate with agricultural systems above to optimize both carbon capture rates and crop yields.",
        potentialScale: "Could sequester 5-10 tons of carbon per acre annually while improving soil health across millions of hectares of degraded land.",
        milestonesForCapital: "1) Lab demonstration of engineered mycelium strains; 2) 10-acre pilot with sensor integration; 3) Regional deployment across 10,000 acres with data integration.",
        teamNeeds: "Mycologists, soil scientists, IoT engineers, machine learning specialists, agricultural technologists.",
        score: 75,
        valueScore: 28,
        innovationScore: 32,
        applicabilityScore: 15
    },
    {
        title: "AI-Enhanced Language Preservation Tools",
        shortDescription: "AI platform preserves endangered languages.",
        technology: "AI, Blockchain",
        values: "Culture",
        problemAddressed: "Thousands of indigenous languages face extinction, threatening cultural heritage and knowledge systems.",
        solutionDetails: "AI-driven platform documents endangered languages, creates interactive learning modules, and offers real-time translation. Communities contribute content preserved on blockchain, ensuring cultural preservation.",
        potentialScale: "Could help preserve 3,000+ endangered languages and associated cultural knowledge while empowering millions of indigenous language speakers.",
        milestonesForCapital: "1) Platform prototype with 10 languages; 2) Full development with 100 languages and active communities; 3) Global platform with 1,000+ languages and educational integration.",
        teamNeeds: "Computational linguists, AI specialists, indigenous knowledge holders, blockchain developers, cultural anthropologists.",
        score: 74,
        valueScore: 29,
        innovationScore: 27,
        applicabilityScore: 18
    },
    {
        title: "Cosmic Soil Symphony",
        shortDescription: "Soil data becomes interactive art.",
        technology: "IoT, Art Tech",
        values: "Creativity",
        problemAddressed: "Disconnection between soil health monitoring and stakeholders limits regenerative agriculture scaling.",
        solutionDetails: "Network of soil sensors translates data into an artistic 'symphony' of sounds and visuals accessible via an app. Farmers, scientists, and artists collaborate on soil regeneration with revenue from artistic outputs funding sustainable farming.",
        potentialScale: "Could monitor and improve tens of millions of hectares while creating novel funding streams for regenerative agriculture.",
        milestonesForCapital: "1) Sensor network prototype with initial sonification; 2) Regional deployment with functional app; 3) Global network with established revenue streams.",
        teamNeeds: "Soil scientists, musicians/composers, data visualization experts, nanotechnology specialists, agricultural outreach coordinators.",
        score: 74,
        valueScore: 26,
        innovationScore: 30,
        applicabilityScore: 18
    },
    {
        title: "Virtual Reality Empathy Training",
        shortDescription: "VR experiences build cross-cultural understanding.",
        technology: "VR, AI",
        values: "Empathy",
        problemAddressed: "Social division and lack of cross-cultural understanding impede solutions to global challenges.",
        solutionDetails: "Immersive VR experiences allow users to experience life as others—refugees, indigenous farmers, endangered animals—with AI personalizing scenarios based on user context and feedback.",
        potentialScale: "Could reach 100M+ users, measurably increasing empathy and cross-cultural understanding while influencing policy and humanitarian support.",
        milestonesForCapital: "1) Proof of concept with 3-5 immersive experiences; 2) Platform launch with 20+ scenarios and impact measurement; 3) Educational and institutional adoption with 100+ experiences.",
        teamNeeds: "VR developers, behavioral psychologists, cultural anthropologists, AI specialists, representatives from portrayed communities.",
        score: 73,
        valueScore: 27,
        innovationScore: 28,
        applicabilityScore: 18
    }
]; 