const ideasData = [
    {
        title: "Smart Soil Regen Tiles",
        shortDescription: "Tiles heal soil with sensors and microbes.",
        technology: "IoT, Biotech",
        values: "Regeneration",
        problemAddressed: "Soil degradation affects 40% of global farmland, slashing yields and resilience.",
        solutionDetails: "Hexagonal tiles (1m²) embed sensors for moisture/pH and release microbial cultures to rebuild soil health. Solar-powered, they sync to a farmer app for real-time data.",
        potentialScale: "Deployable on 1M acres in 5 years, boosting yields 30%.",
        milestonesForCapital: "1) Prototype tested on 10 farms; 2) 1,000 tiles deployed with 20% yield increase; 3) Scale to 100,000 acres.",
        teamNeeds: "Soil scientists, IoT engineers, app developers.",
        score: 89,
        valueScore: 35,
        innovationScore: 36,
        applicabilityScore: 18
    },
    {
        title: "Nomadic Microgrids",
        shortDescription: "Mobile solar units power remote areas.",
        technology: "Renewables, Blockchain",
        values: "Equity",
        problemAddressed: "800M people lack electricity, stunting development.",
        solutionDetails: "Truck-mounted solar/wind units (5kW each) roll into remote areas. Blockchain tracks energy credits, incentivizing surplus sharing.",
        potentialScale: "50,000 homes powered in 3 years across 10 regions.",
        milestonesForCapital: "1) 10-unit pilot in one village; 2) 100 units deployed, 90% uptime; 3) 1,000 units active.",
        teamNeeds: "Renewable engineers, blockchain devs, logistics experts.",
        score: 86,
        valueScore: 34,
        innovationScore: 35,
        applicabilityScore: 17
    },
    {
        title: "Modular Train Systems",
        shortDescription: "Raised trains with solar, wind, farming, and rewilding. Free energy, wildlife thrives.",
        technology: "Renewables, Transport",
        values: "Sustainability",
        problemAddressed: "Transport emissions and land loss disrupt climate and farming.",
        solutionDetails: "Raised tracks with solar panels (500W/m²), wind turbines below, and farming/re-wilding underneath. Trains switch between rail and road with minimal wildlife impact.",
        potentialScale: "1,000km of track, powering 100,000 homes and feeding 50,000 people.",
        milestonesForCapital: "1) 10km prototype built; 2) 100km operational with energy/farm outputs; 3) 500km scaled.",
        teamNeeds: "Transport engineers, renewable experts, ecologists.",
        score: 84,
        valueScore: 32,
        innovationScore: 34,
        applicabilityScore: 18
    },
    {
        title: "Regenerative Bots",
        shortDescription: "Bots apply permaculture to farming at scale.",
        technology: "Robotics, Agriculture",
        values: "Regeneration",
        problemAddressed: "Industrial farming depletes soil and limits scalability of permaculture.",
        solutionDetails: "Autonomous bots (1m wide) plant, tend, and harvest using permaculture patterns. Solar-powered, they adapt to terrain via AI.",
        potentialScale: "10,000 bots on 500,000 acres, doubling soil carbon in a decade.",
        milestonesForCapital: "1) 10-bot pilot on 100 acres; 2) 100 bots with 25% yield gain; 3) 1,000 bots deployed.",
        teamNeeds: "Robotics engineers, permaculture experts, AI developers.",
        score: 83,
        valueScore: 33,
        innovationScore: 33,
        applicabilityScore: 17
    },
    {
        title: "Waste-to-Wear Threads",
        shortDescription: "Plastic waste becomes clothing.",
        technology: "Recycling, AI Design",
        values: "Creativity",
        problemAddressed: "10M tons of plastic waste clog landfills yearly.",
        solutionDetails: "Machines shred plastic into fibers, spun into thread by solar-powered looms. AI designs culturally resonant patterns.",
        potentialScale: "Divert 1M tons, clothe 2M people annually.",
        milestonesForCapital: "1) Prototype machine processes 1 ton; 2) 10 machines, 100 tons diverted; 3) 100 machines scaled.",
        teamNeeds: "Recycling techs, textile designers, AI specialists.",
        score: 81,
        valueScore: 34,
        innovationScore: 31,
        applicabilityScore: 16
    },
    {
        title: "AI Coral Reef Builders",
        shortDescription: "Robots 3D-print coral scaffolds.",
        technology: "Robotics, Marine Biology",
        values: "Biodiversity",
        problemAddressed: "Coral loss threatens 25% of marine life and coastal protection.",
        solutionDetails: "Submersible robots 3D-print scaffolds (bio-cement), seeded with polyps. Drones optimize water flow.",
        potentialScale: "Regrow 50km of reefs in 5 years, protecting 10M coastal residents.",
        milestonesForCapital: "1) 1km scaffold tested; 2) 10km with 80% polyp survival; 3) 50km scaled.",
        teamNeeds: "Marine biologists, robotics engineers, drone operators.",
        score: 81,
        valueScore: 30,
        innovationScore: 34,
        applicabilityScore: 17
    },
    {
        title: "Water-Web Cities",
        shortDescription: "AI grids purify rainwater for urban use.",
        technology: "Water Tech, Clean Energy",
        values: "Resilience",
        problemAddressed: "Urban water scarcity affects 1B people.",
        solutionDetails: "Rooftop pipes harvest rain, biofilters purify it, AI grids distribute it. Excess powers hydrogen buses.",
        potentialScale: "Supply 5M urbanites, cut emissions by 10% in 20 cities.",
        milestonesForCapital: "1) Pilot in 1 city block; 2) 10 blocks with 90% efficiency; 3) Full city rollout.",
        teamNeeds: "Water engineers, AI specialists, urban planners.",
        score: 79,
        valueScore: 31,
        innovationScore: 32,
        applicabilityScore: 16
    },
    {
        title: "Eco-Sound Highways",
        shortDescription: "Roads generate energy, support pollinators.",
        technology: "Energy Harvesting, Ecology",
        values: "Circularity",
        problemAddressed: "Traffic noise and energy waste plague roads.",
        solutionDetails: "Piezoelectric roads (1kW/km) generate power from vibrations. Barriers host pollinator plants, AI tunes noise reduction.",
        potentialScale: "5,000km of roads, powering 200,000 homes.",
        milestonesForCapital: "1) 1km test road; 2) 50km with energy/pollinator gains; 3) 1,000km scaled.",
        teamNeeds: "Energy engineers, ecologists, acoustic experts.",
        score: 78,
        valueScore: 30,
        innovationScore: 31,
        applicabilityScore: 17
    },
    {
        title: "Floating Food Forests",
        shortDescription: "Buoyant platforms grow food with tidal energy.",
        technology: "Hydroponics, Renewables",
        values: "Balance",
        problemAddressed: "Coastal food insecurity and land scarcity.",
        solutionDetails: "100m² platforms use hydroponics and tidal energy. AI optimizes crop cycles, delivers to shore.",
        potentialScale: "1,000 platforms feeding 500,000 people yearly.",
        milestonesForCapital: "1) 1 platform operational; 2) 10 platforms with 50 tons output; 3) 100 platforms scaled.",
        teamNeeds: "Hydroponics experts, maritime engineers, AI devs.",
        score: 77,
        valueScore: 28,
        innovationScore: 32,
        applicabilityScore: 17
    },
    {
        title: "Rewilding Swarm Networks",
        shortDescription: "Drones reforest with satellite tracking.",
        technology: "Drones, Carbon Markets",
        values: "Restoration",
        problemAddressed: "Deforestation wipes out 10M hectares yearly.",
        solutionDetails: "Biodegradable drone swarms (100 units) plant seeds and spray nutrients. Satellites track growth for carbon credits.",
        potentialScale: "Reforest 1M hectares in 5 years, 500Mt CO2 captured.",
        milestonesForCapital: "1) 100-hectare pilot; 2) 10,000 hectares with 70% survival; 3) 100,000 hectares scaled.",
        teamNeeds: "Drone engineers, forestry experts, satellite analysts.",
        score: 77,
        valueScore: 29,
        innovationScore: 33,
        applicabilityScore: 15
    },
    {
        title: "Ocean Energy Harvesters",
        shortDescription: "Drones clean plastic, harvest wave energy.",
        technology: "AI, Ocean Tech",
        values: "Restoration",
        problemAddressed: "Ocean plastic and energy poverty in coastal zones.",
        solutionDetails: "Drones (2m wide) collect plastic and convert wave energy (500W/unit). AI maps cleanup zones.",
        potentialScale: "Clear 500,000 tons of plastic, power 50,000 homes.",
        milestonesForCapital: "1) 10-drone pilot; 2) 100 drones with 1,000 tons cleared; 3) 1,000 drones scaled.",
        teamNeeds: "Ocean techs, AI engineers, energy specialists.",
        score: 75,
        valueScore: 28,
        innovationScore: 31,
        applicabilityScore: 16
    },
    {
        title: "Bio-Mimetic Urban Cooling Drones",
        shortDescription: "Drones cool cities, reforest rooftops.",
        technology: "AI, Drones",
        values: "Harmony",
        problemAddressed: "Urban heat islands raise temps by 5°C+.",
        solutionDetails: "Solar-powered drones (1m span) mist water and drop seeds, mimicking bird flocks. AI targets hotspots.",
        potentialScale: "Cool 50 cities, reforest 10,000 rooftops in 3 years.",
        milestonesForCapital: "1) 10-drone city test; 2) 100 drones, 2°C drop; 3) 1,000 drones scaled.",
        teamNeeds: "Drone engineers, urban ecologists, AI devs.",
        score: 74,
        valueScore: 27,
        innovationScore: 30,
        applicabilityScore: 17
    },
    {
        title: "Sky Farming Towers",
        shortDescription: "Balloon-tethered farms feed cities.",
        technology: "Aerospace, Robotics",
        values: "Innovation",
        problemAddressed: "Land scarcity limits urban food supply.",
        solutionDetails: "50m-high balloon towers grow crops hydroponically. Robots tend and deliver harvests.",
        potentialScale: "Feed 1M city dwellers, free 5,000 acres of land.",
        milestonesForCapital: "1) 1-tower prototype; 2) 5 towers with 100 tons output; 3) 50 towers scaled.",
        teamNeeds: "Aerospace engineers, robotics experts, hydroponics specialists.",
        score: 72,
        valueScore: 25,
        innovationScore: 31,
        applicabilityScore: 16
    }
]; 